package it.unipv.payroll.controller;

import javax.ejb.Stateless;
import javax.inject.Inject;

import it.unipv.payroll.model.Credentials;
import it.unipv.payroll.model.ICredentials;
import it.unipv.payroll.model.IEmployee;
import it.unipv.payroll.utils.Mail;
import it.unipv.payroll.utils.PasswordManager;

@Stateless
public class SessionManagementController extends GenericController<Credentials> {
	@Inject
	Mail mailer;

	private PasswordManager pswdManager = new PasswordManager();

	private boolean areValidCredential(String username, String password) {
		ICredentials loginAttempt = dao.find(username);
		if (loginAttempt != null) {
			// System.out.println(loginAttempt.getPassword());
			// System.out.println(pswdManager.hashIt(password));
			if (loginAttempt.getPassword().equals(pswdManager.hashIt(password))) {
				return true;
			} else {
				return false;
			}
		} else {
			return false;
		}
	}

	public void generateCredentials(IEmployee employee, Credentials credentials) throws Exception {
		credentials.setCode(employee.getCode());
		String password = pswdManager.generatePassword();
		credentials.setPassword(pswdManager.hashIt(password));
		super.add(credentials);
		mailer.send(employee.getEmail(), "Credentials to access the company site", "Access the company website with the following credentials:\n Username: "+employee.getCode()+"\nPassword: "+password+"\n\nIs highly recommended to change your password as soon as possible.\nOnce changed, logout and relog with the new credentials to confirm the changes.\nThis is an autogenerated email, do not reply.");

	}

	@Override
	public Credentials find(Object id) throws Exception {
		String pk=(String)id;
		if (pk == null || pk.isEmpty())
			throw new Exception("Cannot find null or empty id. " + ERROR);
		return dao.find(id);
	}
	
	
	public void changePassword(ICredentials oldest,Credentials newest) throws Exception {
		if(!areValidCredential(oldest.getCode(), oldest.getPassword()))
			throw new Exception("Wrong Password inserted. Please, try again");
		newest.setPassword(pswdManager.hashIt(newest.getPassword()));
		super.update(newest);
	}

	@Override
	public boolean isAlreadyInDatabase(Credentials element) {
		ICredentials login = dao.find(element.getCode());
		if (login != null) {
			return true;
		}
		return false;
	}

	@Override
	public boolean isElementOk(Credentials element) {
		if (element.getCode().isEmpty() || element.getCode() == null)
			return false;
		if (element.getPassword().isEmpty() || element.getPassword() == null)
			return false;
		return true;
	}

}
