package it.unipv.payroll.utils;

import java.util.Date;
import java.util.HashMap;
import java.util.Set;

import com.itextpdf.text.Chapter;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Section;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;

import it.unipv.payroll.model.Employee;

public class PdfGenerator {

	private static Font bigFont = new Font(Font.FontFamily.TIMES_ROMAN, 18, Font.BOLD);

	
	public Document generatePdf(HashMap<Employee, Float> earnings) throws DocumentException{
		Document document = new Document();
		document.addTitle("Payments " + (new Date()).toString());
		document.addCreator("Automatically generated by the payrollSystem");
		Chapter chapter = new Chapter(new Paragraph("Payments " + (new Date()).toString(), bigFont), 1);
		Paragraph sectionParagraph1=new Paragraph("Completed payments");
		generateAndAddTable(earnings, chapter, sectionParagraph1);
		document.add(chapter);
		return document;
	}


	private void generateAndAddTable(HashMap<Employee, Float> earnings, Chapter chapter, Paragraph sectionParagraph) {
		Section section= chapter.addSection(sectionParagraph);
		PdfPTable tabella = new PdfPTable(3);
		
		PdfPCell c1 = new PdfPCell(new Phrase("Employee Code"));
		c1.setHorizontalAlignment(Element.ALIGN_CENTER);
		c1.setGrayFill(0.8f);
		tabella.addCell(c1);

		c1 = new PdfPCell(new Phrase("Employee Surname"));
		c1.setHorizontalAlignment(Element.ALIGN_CENTER);
		c1.setGrayFill(0.8f);
		tabella.addCell(c1);

		c1 = new PdfPCell(new Phrase("Employee Name"));
		c1.setHorizontalAlignment(Element.ALIGN_CENTER);
		c1.setGrayFill(0.8f);
		tabella.addCell(c1);

		c1 = new PdfPCell(new Phrase("Amount"));
		c1.setHorizontalAlignment(Element.ALIGN_CENTER);
		c1.setGrayFill(0.8f);
		tabella.addCell(c1);
		
		c1 = new PdfPCell(new Phrase("Payment details (if any)"));
		c1.setHorizontalAlignment(Element.ALIGN_CENTER);
		c1.setGrayFill(0.8f);
		tabella.addCell(c1);

		tabella.setHeaderRows(1);
		Set<Employee> keySet=earnings.keySet();
		for (Employee employee : keySet) {
			tabella.addCell(employee.getCode());
			tabella.addCell(employee.getName());
			tabella.addCell(employee.getSurname());
			tabella.addCell(earnings.get(employee)+"");
			tabella.addCell(employee.getPayment_method_details());
		}
		
		section.add(tabella);
	}
	
}
